import serial
import time
from pynput.keyboard import Key, Controller                                                                         
#Enter Your Arduino Port Number
ser = serial.Serial('COM2', 9600)
keyboard = Controller()
while True:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    data = ser.readline()
    
    if data.decode().strip() == "d":
        keyboard.press(Key.space)
        keyboard.release(Key.space)
                                                                                                                                                                                                                                                                                                                                                        
